# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Associated Eye Physicians
email: abertolucci@njeyedocs.com
description: >- # this means to ignore newlines until "baseurl:"
  Associated Eye Physicians - Established group of physicians providing professional and personalized eye care for all ages using the latest
  laser technology to diagonse and treat people in the Northern New Jersey area - Elizabeth, Newark, Pompton Lakes, and Westfield.  
url: "http://njeyedocs.com" # the base hostname & protocol for your site, e.g. http://example.com
repository: "poojandpatel/associated-eye-physicians"
logo: "/assets/images/aep_logo.png"
masthead_title: ""

include:
  - _pages

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-seo-tag

atom_feed:
  hide: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      classes: wide
      author_profile: false
      layout: single
  
author:
  name: Alessandra Bertolucci, MD, FAAO
  bio: Eye Care Specialist
  avatar: /assets/images/providers/alessandra_bertolucci.jpeg
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:cornelius@thewhip.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/rhymeswithsackit"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
